"""Trajectory figures.

Everything matplotlib-related lives here so that :mod:`sixdof.trajectory` stays
importable inside a Monte Carlo loop without pulling in a plotting backend.

The eighteen figures of the original engine are reproduced with the same file
names and the same styling.  The vs-time / vs-distance pairs are generated by a
single private helper parameterised on the abscissa, which is where most of the
duplication in the original file was.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Callable, Optional, Sequence, Tuple, Union

import numpy as np

if TYPE_CHECKING:  # pragma: no cover
    from matplotlib.axes import Axes
    from matplotlib.figure import Figure

    from .trajectory import Trajectory

PathLike = Union[str, "os.PathLike[str]"]


@dataclass(frozen=True)
class Palette:
    """Colour scheme for the figures.

    The default is the light, high-contrast palette used in the thesis
    (3Blue1Brown-inspired, white background so the plots print well).
    """

    bg: str = "#FFFFFF"
    primary: str = "#1A7FA0"
    secondary: str = "#2E5F7D"
    accent1: str = "#3BA3C7"
    accent2: str = "#1A5F7A"
    grid: str = "#D0D0D0"
    text: str = "#1A1A1A"
    green: str = "#2E7D32"
    red: str = "#C62828"
    yellow: str = "#F9A825"
    purple: str = "#6A1B9A"
    orange: str = "#EF6C00"


DEFAULT_PALETTE = Palette()

#: File name of every figure, keyed by the plotter method that produces it.
FIGURE_FILENAMES = {
    "plot_trajectory_3d": "01_trajectory_3d_white.png",
    "plot_top_view": "02_top_view_white.png",
    "plot_side_view": "03_side_view_white.png",
    "plot_velocity_vs_time": "04_velocity_vs_time_white.png",
    "plot_velocity_vs_distance": "05_velocity_vs_distance_white.png",
    "plot_axis_orientation_vs_time": "06_axis_orientation_vs_time_white.png",
    "plot_axis_orientation_vs_distance": "07_axis_orientation_vs_distance_white.png",
    "plot_angular_momentum_vs_time": "08_angular_momentum_vs_time_white.png",
    "plot_angular_momentum_vs_distance": "09_angular_momentum_vs_distance_white.png",
    "plot_angle_of_attack_vs_time": "10_angle_of_attack_vs_time_white.png",
    "plot_angle_of_attack_vs_distance": "11_angle_of_attack_vs_distance_white.png",
    "plot_mach_vs_time": "12_mach_vs_time_white.png",
    "plot_mach_vs_distance": "13_mach_vs_distance_white.png",
    "plot_spin_rate_vs_time": "14_spin_rate_vs_time_white.png",
    "plot_spin_rate_vs_distance": "15_spin_rate_vs_distance_white.png",
    "plot_altitude_vs_time": "16_altitude_vs_time_white.png",
    "plot_lateral_drift_vs_time": "17_lateral_drift_vs_time_white.png",
    "plot_range_vs_time": "18_range_vs_time_white.png",
}

_TIME_LABEL = "Tempo [s]"
_RANGE_LABEL = "Alcance [km]"


class TrajectoryPlotter:
    """Draw the standard figure set for one :class:`~sixdof.trajectory.Trajectory`.

    Parameters
    ----------
    trajectory:
        The trajectory to plot.
    palette:
        Colour scheme; defaults to :data:`DEFAULT_PALETTE`.
    output_dir:
        Directory the PNGs are written to.  Created if missing.
    show:
        Call ``plt.show()`` after each figure.  Set to ``False`` for batch runs
        and in tests, where a blocking window would hang the process.
    dpi:
        Resolution of the saved PNGs.

    Examples
    --------
    >>> TrajectoryPlotter(trajectory, output_dir="figures", show=False).plot_all()
    """

    def __init__(
        self,
        trajectory: "Trajectory",
        palette: Palette = DEFAULT_PALETTE,
        output_dir: PathLike = ".",
        show: bool = True,
        dpi: int = 200,
    ) -> None:
        self.trajectory = trajectory
        self.palette = palette
        self.output_dir = Path(output_dir)
        self.show = show
        self.dpi = dpi

    # ------------------------------------------------------------------
    # infrastructure
    # ------------------------------------------------------------------
    @staticmethod
    def _pyplot():
        """Import pyplot lazily so importing this module stays cheap."""
        import matplotlib.pyplot as plt

        return plt

    def _resolve(self, save_path: Optional[PathLike], default_name: str) -> Path:
        path = Path(save_path) if save_path is not None else self.output_dir / default_name
        path.parent.mkdir(parents=True, exist_ok=True)
        return path

    def _style_axes(self, ax: "Axes", title: str = "") -> None:
        """Apply the shared axis styling (white ground, soft grid, dark text)."""
        c = self.palette
        ax.set_facecolor(c.bg)
        ax.grid(True, alpha=0.4, color=c.grid, linestyle="-", linewidth=0.8)
        ax.tick_params(colors=c.text, labelsize=10)
        for side in ("bottom", "top", "right", "left"):
            ax.spines[side].set_color(c.text)
            ax.spines[side].set_linewidth(1.5)
        ax.xaxis.label.set_color(c.text)
        ax.yaxis.label.set_color(c.text)
        ax.title.set_color(c.text)
        if title:
            ax.set_title(title, fontsize=14, fontweight="bold", pad=15)

    def _legend(self, ax: "Axes", fontsize: int = 10, loc: str = "best") -> None:
        """Legend with the palette's text colour applied to every entry."""
        legend = ax.legend(
            facecolor=self.palette.bg,
            edgecolor=self.palette.text,
            fontsize=fontsize,
            loc=loc,
            framealpha=1,
        )
        for text in legend.get_texts():
            text.set_color(self.palette.text)

    def _finish(self, fig: "Figure", path: Path) -> None:
        """Tighten, save, announce and optionally display the figure."""
        plt = self._pyplot()
        plt.tight_layout()
        plt.savefig(path, dpi=self.dpi, facecolor=self.palette.bg, bbox_inches="tight")
        print(f"✓ Gráfico salvo: {path}")
        if self.show:
            plt.show()
        else:
            plt.close(fig)

    def _abscissa(self, against: str) -> Tuple[np.ndarray, str]:
        """Return the x data and its label for ``'time'`` or ``'distance'``."""
        if against == "time":
            return self.trajectory.t, _TIME_LABEL
        if against == "distance":
            return self.trajectory.x / 1000, _RANGE_LABEL
        raise ValueError("against must be 'time' or 'distance'")

    # ------------------------------------------------------------------
    # spatial views
    # ------------------------------------------------------------------
    def plot_trajectory_3d(self, save_path: Optional[PathLike] = None) -> Path:
        """Figure 1: the trajectory in three dimensions."""
        plt = self._pyplot()
        traj, c = self.trajectory, self.palette
        path = self._resolve(save_path, FIGURE_FILENAMES["plot_trajectory_3d"])

        fig = plt.figure(figsize=(12, 10), facecolor=c.bg)
        ax = fig.add_subplot(111, projection="3d")
        ax.set_facecolor(c.bg)

        ax.plot(traj.x / 1000, traj.z, traj.y / 1000, color=c.primary, linewidth=3, alpha=0.9)
        ax.scatter(
            [0], [0], [0], c=c.green, s=200, marker="o",
            edgecolors=c.text, linewidths=2.5, label="Início",
        )
        ax.scatter(
            [traj.x[-1] / 1000], [traj.z[-1]], [traj.y[-1] / 1000],
            c=c.red, s=200, marker="X", edgecolors=c.text, linewidths=2.5, label="Impacto",
        )

        ax.set_xlabel(_RANGE_LABEL, fontsize=12, fontweight="bold", color=c.text, labelpad=10)
        ax.set_ylabel("Deriva Lateral [m]", fontsize=12, fontweight="bold", color=c.text, labelpad=10)
        ax.set_zlabel("Altitude [km]", fontsize=12, fontweight="bold", color=c.text, labelpad=10)
        ax.set_title("Trajetória 3D Completa", fontsize=16, fontweight="bold", color=c.text, pad=20)

        ax.tick_params(colors=c.text)
        for pane in (ax.xaxis.pane, ax.yaxis.pane, ax.zaxis.pane):
            pane.fill = False
            pane.set_edgecolor(c.grid)
        ax.grid(True, alpha=0.3, color=c.grid)
        self._legend(ax, loc="upper left")

        self._finish(fig, path)
        return path

    def plot_top_view(self, save_path: Optional[PathLike] = None) -> Path:
        """Figure 2: plan view, showing the lateral drift."""
        plt = self._pyplot()
        traj, c = self.trajectory, self.palette
        path = self._resolve(save_path, FIGURE_FILENAMES["plot_top_view"])

        fig, ax = plt.subplots(figsize=(14, 6), facecolor=c.bg)
        self._style_axes(ax, "Vista de Cima - Deriva Lateral")

        ax.plot(traj.x / 1000, traj.z, color=c.primary, linewidth=3, alpha=0.9)
        ax.scatter([traj.x[0] / 1000], [traj.z[0]], c=c.green, s=200, marker="o",
                   edgecolors=c.text, linewidths=2.5, label="Início", zorder=5)
        ax.scatter([traj.x[-1] / 1000], [traj.z[-1]], c=c.red, s=200, marker="X",
                   edgecolors=c.text, linewidths=2.5, label="Impacto", zorder=5)
        ax.axhline(y=0, color=c.yellow, linestyle="--", alpha=0.7, linewidth=2,
                   label="Referência (Z=0)")

        ax.set_xlabel(_RANGE_LABEL, fontsize=12, fontweight="bold")
        ax.set_ylabel("Deriva Lateral [m]", fontsize=12, fontweight="bold")
        self._legend(ax)

        self._finish(fig, path)
        return path

    def plot_side_view(self, save_path: Optional[PathLike] = None) -> Path:
        """Figure 3: elevation view, the vertical profile."""
        plt = self._pyplot()
        traj, c = self.trajectory, self.palette
        path = self._resolve(save_path, FIGURE_FILENAMES["plot_side_view"])

        fig, ax = plt.subplots(figsize=(14, 6), facecolor=c.bg)
        self._style_axes(ax, "Vista Lateral - Perfil Vertical")

        ax.fill_between(traj.x / 1000, 0, traj.y / 1000, alpha=0.15, color=c.primary)
        ax.plot(traj.x / 1000, traj.y / 1000, color=c.primary, linewidth=3, alpha=0.9)
        ax.scatter([traj.x[0] / 1000], [traj.y[0] / 1000], c=c.green, s=200, marker="o",
                   edgecolors=c.text, linewidths=2.5, label="Início", zorder=5)
        ax.scatter([traj.x[-1] / 1000], [traj.y[-1] / 1000], c=c.red, s=200, marker="X",
                   edgecolors=c.text, linewidths=2.5, label="Impacto", zorder=5)
        ax.axhline(y=0, color=c.text, linestyle="-", alpha=0.8, linewidth=2.5,
                   label="Nível do Solo")

        ax.set_xlabel(_RANGE_LABEL, fontsize=12, fontweight="bold")
        ax.set_ylabel("Altitude [km]", fontsize=12, fontweight="bold")
        self._legend(ax)

        self._finish(fig, path)
        return path

    # ------------------------------------------------------------------
    # paired time / distance series
    # ------------------------------------------------------------------
    def _plot_components(
        self,
        against: str,
        title: str,
        ylabel: str,
        series: Sequence[Tuple[np.ndarray, str, str, float, str]],
        default_name: str,
        save_path: Optional[PathLike],
        zero_line: bool = False,
    ) -> Path:
        """Shared body of the multi-component series figures.

        ``series`` entries are ``(values, colour, label, linewidth, linestyle)``.
        """
        plt = self._pyplot()
        c = self.palette
        path = self._resolve(save_path, default_name)
        xdata, xlabel = self._abscissa(against)

        fig, ax = plt.subplots(figsize=(14, 8), facecolor=c.bg)
        self._style_axes(ax, title)

        for values, colour, label, linewidth, linestyle in series:
            ax.plot(
                xdata, values, color=colour, linewidth=linewidth,
                linestyle=linestyle, alpha=0.9 if linestyle == "-" else 0.8, label=label,
            )

        if zero_line:
            ax.axhline(y=0, color=c.text, linestyle=":", linewidth=1.5, alpha=0.5)

        ax.set_xlabel(xlabel, fontsize=12, fontweight="bold")
        ax.set_ylabel(ylabel, fontsize=12, fontweight="bold")
        self._legend(ax, fontsize=11 if zero_line else 10)

        self._finish(fig, path)
        return path

    def plot_velocity(self, against: str = "time", save_path: Optional[PathLike] = None) -> Path:
        """Figures 4-5: velocity magnitude and components."""
        traj, c = self.trajectory, self.palette
        name = FIGURE_FILENAMES[f"plot_velocity_vs_{against}"]
        return self._plot_components(
            against,
            f"Velocidade vs {'Tempo' if against == 'time' else 'Distância'}",
            "Velocidade [m/s]",
            [
                (traj.V_mag, c.primary, "|V| (Magnitude)", 3.5, "-"),
                (traj.V1, c.accent1, "V₁ (Forward)", 2.5, "--"),
                (traj.V2, c.green, "V₂ (Up)", 2.5, "--"),
                (traj.V3, c.purple, "V₃ (Right)", 2.5, "--"),
            ],
            name,
            save_path,
        )

    def plot_axis_orientation(
        self, against: str = "time", save_path: Optional[PathLike] = None
    ) -> Path:
        """Figures 6-7: components of the axis of symmetry ``i'``."""
        traj, c = self.trajectory, self.palette
        name = FIGURE_FILENAMES[f"plot_axis_orientation_vs_{against}"]
        return self._plot_components(
            against,
            f"Evolução do Eixo Polar i' vs {'Tempo' if against == 'time' else 'Distância'}",
            "Componentes de i'",
            [
                (traj.i1, c.red, "i'₁", 3, "-"),
                (traj.i2, c.green, "i'₂", 3, "-"),
                (traj.i3, c.accent1, "i'₃", 3, "-"),
            ],
            name,
            save_path,
            zero_line=True,
        )

    def plot_angular_momentum(
        self, against: str = "time", save_path: Optional[PathLike] = None
    ) -> Path:
        """Figures 8-9: angular momentum magnitude and components."""
        traj, c = self.trajectory, self.palette
        name = FIGURE_FILENAMES[f"plot_angular_momentum_vs_{against}"]
        return self._plot_components(
            against,
            f"Momento Angular vs {'Tempo' if against == 'time' else 'Distância'}",
            "Momento Angular [rad/s]",
            [
                (traj.h_mag, c.primary, "|h| (Magnitude)", 3.5, "-"),
                (traj.h1, c.red, "h₁", 2.5, "--"),
                (traj.h2, c.green, "h₂", 2.5, "--"),
                (traj.h3, c.accent1, "h₃", 2.5, "--"),
            ],
            name,
            save_path,
        )

    def plot_angle_of_attack(
        self, against: str = "time", save_path: Optional[PathLike] = None
    ) -> Path:
        """Figures 10-11: total angle of attack, shaded by sign."""
        plt = self._pyplot()
        traj, c = self.trajectory, self.palette
        path = self._resolve(save_path, FIGURE_FILENAMES[f"plot_angle_of_attack_vs_{against}"])
        xdata, xlabel = self._abscissa(against)

        fig, ax = plt.subplots(figsize=(14, 8), facecolor=c.bg)
        self._style_axes(
            ax, f"Ângulo de Ataque vs {'Tempo' if against == 'time' else 'Distância'}"
        )

        ax.plot(xdata, traj.alpha_traj, color=c.primary, linewidth=3, alpha=0.9)
        ax.fill_between(xdata, 0, traj.alpha_traj, where=(traj.alpha_traj >= 0),
                        color=c.green, alpha=0.25, label="α positivo")
        ax.fill_between(xdata, 0, traj.alpha_traj, where=(traj.alpha_traj < 0),
                        color=c.red, alpha=0.25, label="α negativo")
        ax.axhline(y=0, color=c.text, linestyle=":", linewidth=1.5, alpha=0.6)

        ax.set_xlabel(xlabel, fontsize=12, fontweight="bold")
        ax.set_ylabel("Ângulo de Ataque [°]", fontsize=12, fontweight="bold")
        self._legend(ax)

        self._finish(fig, path)
        return path

    def plot_mach(self, against: str = "time", save_path: Optional[PathLike] = None) -> Path:
        """Figures 12-13: Mach number, with the transonic boundary marked."""
        plt = self._pyplot()
        traj, c = self.trajectory, self.palette
        path = self._resolve(save_path, FIGURE_FILENAMES[f"plot_mach_vs_{against}"])
        xdata, xlabel = self._abscissa(against)

        fig, ax = plt.subplots(figsize=(14, 8), facecolor=c.bg)
        self._style_axes(
            ax, f"Número de Mach vs {'Tempo' if against == 'time' else 'Distância'}"
        )

        ax.plot(xdata, traj.mach, color=c.purple, linewidth=3, alpha=0.9, label="Mach")
        ax.axhline(y=1.0, color=c.red, linestyle="--", alpha=0.8, linewidth=2.5,
                   label="Mach 1 (Barreira do Som)")
        ax.fill_between(xdata, 0, traj.mach, where=(traj.mach >= 1.0),
                        color=c.red, alpha=0.15, label="Supersônico")
        ax.fill_between(xdata, 0, traj.mach, where=(traj.mach < 1.0),
                        color=c.green, alpha=0.15, label="Subsônico")

        ax.set_xlabel(xlabel, fontsize=12, fontweight="bold")
        ax.set_ylabel("Número de Mach", fontsize=12, fontweight="bold")
        self._legend(ax)

        self._finish(fig, path)
        return path

    def plot_spin_rate(self, against: str = "time", save_path: Optional[PathLike] = None) -> Path:
        """Figures 14-15: axial spin decay against the muzzle value."""
        plt = self._pyplot()
        traj, c = self.trajectory, self.palette
        path = self._resolve(save_path, FIGURE_FILENAMES[f"plot_spin_rate_vs_{against}"])
        xdata, xlabel = self._abscissa(against)

        initial_spin = traj.projectile.calculate_initial_spin(traj.muzzle_velocity)

        fig, ax = plt.subplots(figsize=(14, 8), facecolor=c.bg)
        self._style_axes(
            ax, f"Taxa de Spin vs {'Tempo' if against == 'time' else 'Distância'}"
        )

        ax.plot(xdata, traj.spin_rate, color=c.orange, linewidth=3, alpha=0.9,
                label="Spin Atual")
        ax.axhline(y=initial_spin, color=c.yellow, linestyle=":", alpha=0.8, linewidth=2.5,
                   label="Spin Inicial")

        ax.set_xlabel(xlabel, fontsize=12, fontweight="bold")
        ax.set_ylabel("Taxa de Spin [rad/s]", fontsize=12, fontweight="bold")
        self._legend(ax)

        self._finish(fig, path)
        return path

    # ------------------------------------------------------------------
    # single-abscissa figures
    # ------------------------------------------------------------------
    def plot_altitude_vs_time(self, save_path: Optional[PathLike] = None) -> Path:
        """Figure 16: altitude history, apogee marked."""
        plt = self._pyplot()
        traj, c = self.trajectory, self.palette
        path = self._resolve(save_path, FIGURE_FILENAMES["plot_altitude_vs_time"])

        fig, ax = plt.subplots(figsize=(14, 8), facecolor=c.bg)
        self._style_axes(ax, "Altitude vs Tempo")

        ax.fill_between(traj.t, 0, traj.y / 1000, alpha=0.15, color=c.primary)
        ax.plot(traj.t, traj.y / 1000, color=c.primary, linewidth=3, alpha=0.9, label="Altitude")

        idx_max_alt = int(np.argmax(traj.y))
        ax.scatter([traj.t[idx_max_alt]], [traj.y[idx_max_alt] / 1000], c=c.red, s=200,
                   marker="*", edgecolors=c.text, linewidths=2.5,
                   label=f"Altura Máxima: {traj.max_altitude/1000:.2f} km", zorder=5)
        ax.axhline(y=0, color=c.text, linestyle="-", alpha=0.8, linewidth=2.5,
                   label="Nível do Solo")

        ax.set_xlabel(_TIME_LABEL, fontsize=12, fontweight="bold")
        ax.set_ylabel("Altitude [km]", fontsize=12, fontweight="bold")
        self._legend(ax)

        self._finish(fig, path)
        return path

    def plot_lateral_drift_vs_time(self, save_path: Optional[PathLike] = None) -> Path:
        """Figure 17: lateral drift history, shaded by sign."""
        plt = self._pyplot()
        traj, c = self.trajectory, self.palette
        path = self._resolve(save_path, FIGURE_FILENAMES["plot_lateral_drift_vs_time"])

        fig, ax = plt.subplots(figsize=(14, 8), facecolor=c.bg)
        self._style_axes(ax, "Desvio Lateral vs Tempo")

        ax.plot(traj.t, traj.z, color=c.accent1, linewidth=3, alpha=0.9,
                label="Desvio Lateral (Z)")
        ax.fill_between(traj.t, 0, traj.z, where=(traj.z >= 0), color=c.green, alpha=0.2,
                        label="Desvio positivo")
        ax.fill_between(traj.t, 0, traj.z, where=(traj.z < 0), color=c.red, alpha=0.2,
                        label="Desvio negativo")
        ax.axhline(y=0, color=c.yellow, linestyle="--", alpha=0.7, linewidth=2,
                   label="Referência (Z=0)")

        idx_max_z = int(np.argmax(np.abs(traj.z)))
        ax.scatter([traj.t[idx_max_z]], [traj.z[idx_max_z]], c=c.purple, s=200, marker="D",
                   edgecolors=c.text, linewidths=2.5,
                   label=f"Desvio Máx: {np.abs(traj.z[idx_max_z]):.2f} m", zorder=5)

        ax.set_xlabel(_TIME_LABEL, fontsize=12, fontweight="bold")
        ax.set_ylabel("Desvio Lateral [m]", fontsize=12, fontweight="bold")
        self._legend(ax)

        self._finish(fig, path)
        return path

    def plot_range_vs_time(self, save_path: Optional[PathLike] = None) -> Path:
        """Figure 18: downrange distance history."""
        plt = self._pyplot()
        traj, c = self.trajectory, self.palette
        path = self._resolve(save_path, FIGURE_FILENAMES["plot_range_vs_time"])

        fig, ax = plt.subplots(figsize=(14, 8), facecolor=c.bg)
        self._style_axes(ax, "Alcance vs Tempo")

        ax.fill_between(traj.t, 0, traj.x / 1000, alpha=0.15, color=c.secondary)
        ax.plot(traj.t, traj.x / 1000, color=c.secondary, linewidth=3, alpha=0.9,
                label="Alcance (X)")
        ax.scatter([traj.t[-1]], [traj.x[-1] / 1000], c=c.red, s=200, marker="X",
                   edgecolors=c.text, linewidths=2.5,
                   label=f"Alcance Final: {traj.max_range/1000:.2f} km", zorder=5)

        ax.set_xlabel(_TIME_LABEL, fontsize=12, fontweight="bold")
        ax.set_ylabel(_RANGE_LABEL, fontsize=12, fontweight="bold")
        self._legend(ax)

        self._finish(fig, path)
        return path

    # ------------------------------------------------------------------
    # thin wrappers keeping the original method names
    # ------------------------------------------------------------------
    def plot_velocity_vs_time(self, save_path: Optional[PathLike] = None) -> Path:
        return self.plot_velocity("time", save_path)

    def plot_velocity_vs_distance(self, save_path: Optional[PathLike] = None) -> Path:
        return self.plot_velocity("distance", save_path)

    def plot_axis_orientation_vs_time(self, save_path: Optional[PathLike] = None) -> Path:
        return self.plot_axis_orientation("time", save_path)

    def plot_axis_orientation_vs_distance(self, save_path: Optional[PathLike] = None) -> Path:
        return self.plot_axis_orientation("distance", save_path)

    def plot_angular_momentum_vs_time(self, save_path: Optional[PathLike] = None) -> Path:
        return self.plot_angular_momentum("time", save_path)

    def plot_angular_momentum_vs_distance(self, save_path: Optional[PathLike] = None) -> Path:
        return self.plot_angular_momentum("distance", save_path)

    def plot_angle_of_attack_vs_time(self, save_path: Optional[PathLike] = None) -> Path:
        return self.plot_angle_of_attack("time", save_path)

    def plot_angle_of_attack_vs_distance(self, save_path: Optional[PathLike] = None) -> Path:
        return self.plot_angle_of_attack("distance", save_path)

    def plot_mach_vs_time(self, save_path: Optional[PathLike] = None) -> Path:
        return self.plot_mach("time", save_path)

    def plot_mach_vs_distance(self, save_path: Optional[PathLike] = None) -> Path:
        return self.plot_mach("distance", save_path)

    def plot_spin_rate_vs_time(self, save_path: Optional[PathLike] = None) -> Path:
        return self.plot_spin_rate("time", save_path)

    def plot_spin_rate_vs_distance(self, save_path: Optional[PathLike] = None) -> Path:
        return self.plot_spin_rate("distance", save_path)

    # ------------------------------------------------------------------
    # batch
    # ------------------------------------------------------------------
    def plot_all(self) -> Sequence[Path]:
        """Generate the full eighteen-figure set, in the original order."""
        print("\n" + "=" * 80)
        print("GERANDO TODOS OS GRÁFICOS (ESTILO 3BLUE1BROWN - FUNDO BRANCO)")
        print("=" * 80)

        methods: Sequence[Callable[[], Path]] = [
            self.plot_trajectory_3d,
            self.plot_top_view,
            self.plot_side_view,
            self.plot_velocity_vs_time,
            self.plot_velocity_vs_distance,
            self.plot_axis_orientation_vs_time,
            self.plot_axis_orientation_vs_distance,
            self.plot_angular_momentum_vs_time,
            self.plot_angular_momentum_vs_distance,
            self.plot_angle_of_attack_vs_time,
            self.plot_angle_of_attack_vs_distance,
            self.plot_mach_vs_time,
            self.plot_mach_vs_distance,
            self.plot_spin_rate_vs_time,
            self.plot_spin_rate_vs_distance,
            self.plot_altitude_vs_time,
            self.plot_lateral_drift_vs_time,
            self.plot_range_vs_time,
        ]
        paths = [method() for method in methods]

        print("\n✓ Todos os gráficos foram gerados!")
        return paths


__all__ = ["TrajectoryPlotter", "Palette", "DEFAULT_PALETTE", "FIGURE_FILENAMES"]
